apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: nginx-bhanu
      image: nginx
      ports:
      - containerPort: 8080
    - name: watcher-bhanu
      image: afakharany/watcher
      ports:
      - containerPort: 8081
